'use client';
import { useState, type FormEvent } from 'react';
import { LocationFields, optionalCoordinates } from './LocationFields';
import { apiJson } from '../lib/api';
export type BloodRequest = { id: string; bloodGroup: string; units: number; urgency: string; hospitalName: string; city: string; latitude: string | null; longitude: string | null; expiresAt: string; status: string; createdAt: string };
const groups=['O-','O+','A-','A+','B-','B+','AB-','AB+'];
function localDateTime(value:string){const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function RequestForm({ initial, onSaved }: { initial?: BloodRequest; onSaved: (request: BloodRequest) => void }) {
  const [pending,setPending]=useState(false);const [error,setError]=useState('');
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError('');const data=new FormData(event.currentTarget);
    try{const path=initial?`/requests/${initial.id}`:'/requests';const result=await apiJson<BloodRequest>(path,{method:initial?'PATCH':'POST',body:JSON.stringify({bloodGroup:data.get('bloodGroup'),units:Number(data.get('units')),urgency:data.get('urgency'),hospitalName:data.get('hospitalName'),city:data.get('city'),expiresAt:new Date(String(data.get('expiresAt'))).toISOString(),...optionalCoordinates(data)})});onSaved(result);}catch(message){setError(String(message instanceof Error?message.message:message));}finally{setPending(false);}}
  return <form className="stacked-form" onSubmit={submit}><div className="field-grid"><label>Blood group needed<select name="bloodGroup" defaultValue={initial?.bloodGroup||''} required><option value="" disabled>Select a group</option>{groups.map(group=><option key={group}>{group}</option>)}</select></label><label>Units needed<input name="units" type="number" min="1" max="20" defaultValue={initial?.units||1} required /></label></div><div className="field-grid"><label>Urgency<select name="urgency" defaultValue={initial?.urgency||'NORMAL'}><option value="NORMAL">Normal</option><option value="URGENT">Urgent</option></select></label><label>Expires at<input name="expiresAt" type="datetime-local" defaultValue={initial?localDateTime(initial.expiresAt):''} required /></label></div><label>Hospital or care center<input name="hospitalName" minLength={2} maxLength={120} defaultValue={initial?.hospitalName||''} required /></label><label>City<input name="city" minLength={2} maxLength={100} defaultValue={initial?.city||''} required /></label><LocationFields initialLatitude={initial?.latitude?Number(initial.latitude):null} initialLongitude={initial?.longitude?Number(initial.longitude):null}/><p className="hint">Requests expire between 15 minutes and 30 days from now. Donors see the hospital, city, blood group and urgency. Your identity stays private until a donor responds.</p><button disabled={pending}>{pending?'Saving…':initial?'Save changes':'Create request'}</button>{error&&<p role="alert" className="error">{error}</p>}</form>;
}
