'use client';
import { useEffect,useState } from 'react';
import { useParams } from 'next/navigation';
import { AccountGate } from '../../../components/AccountGate';
import { RequestForm,type BloodRequest } from '../../../components/RequestForm';
import { apiJson } from '../../../lib/api';
type Match={id:string;bloodGroup:string;city:string;distanceKm:number|null};
type Interest={id:string;consentAt:string;donor:{bloodGroup:string;city:string;user:{fullName:string;email:string}}};
function Detail({id}:{id:string}){const [request,setRequest]=useState<BloodRequest|null>(null);const [matches,setMatches]=useState<Match[]>([]);const [interests,setInterests]=useState<Interest[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [editing,setEditing]=useState(false);
  async function load(){setError('');try{const [item,matched,responded]=await Promise.all([apiJson<BloodRequest>(`/requests/${id}`),apiJson<Match[]>(`/requests/${id}/matches`),apiJson<Interest[]>(`/requests/${id}/interests`)]);setRequest(item);setMatches(matched);setInterests(responded);}catch{setError('Unable to load this request. It may have been removed or belong to another account.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[id]);
  async function close(){if(!request)return;setError('');try{await apiJson(`/requests/${request.id}`,{method:'DELETE'});setNotice('Request closed.');await load();}catch{setError('Could not close the request. Try again.');}}
  return <section><a href="/requests">← Your requests</a>{loading?<p role="status">Loading request…</p>:error?<div role="alert"><p className="error">{error}</p><button onClick={()=>void load()}>Retry</button></div>:request?<><div className="section-heading"><div><h1>{request.hospitalName}</h1><p>{request.bloodGroup} · {request.units} unit{request.units===1?'':'s'} · {request.city} · {request.status.toLowerCase()}</p></div>{request.status==='OPEN'&&<div className="actions"><button className="secondary" onClick={()=>setEditing(!editing)}>{editing?'Cancel edit':'Edit request'}</button><button onClick={()=>void close()}>Close request</button></div>}</div><p>Expires {new Date(request.expiresAt).toLocaleString()}</p>{notice&&<p role="status" className="success">{notice}</p>}{editing&&<div className="content-panel"><h2>Edit request</h2><RequestForm initial={request} onSaved={updated=>{setRequest(updated);setEditing(false);setNotice('Request updated. Previous donor responses were cleared because the details changed.');void load();}}/></div>}<div className="two-column"><section><h2>Matching donors</h2><p>These approved donors opted into anonymous matching. Contact details appear only after they respond.</p>{matches.length===0?<p className="empty">No matching donors found yet.</p>:<ul className="simple-list">{matches.map(match=><li key={match.id}>{match.bloodGroup} donor · {match.city}{match.distanceKm!==null?` · ${match.distanceKm} km`:''}</li>)}</ul>}</section><section><h2>Donors who responded</h2>{interests.length===0?<p className="empty">No donor has responded yet.</p>:<ul className="simple-list">{interests.map(item=><li key={item.id}><strong>{item.donor.user.fullName}</strong> · {item.donor.bloodGroup} · {item.donor.city}<br/><a href={`mailto:${item.donor.user.email}`}>{item.donor.user.email}</a></li>)}</ul>}</section></div></>:null}</section>;
}
export default function RequestDetailPage(){const params=useParams<{id:string}>();return <AccountGate role="USER">{()=> <Detail id={params.id}/>}</AccountGate>}
